---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -d '{ignore: "../../hosts.yml"}' .
  ansible-lint -r bug
  flake8
platforms:
  - name: ui-host
    groups:
      - example
    children:
      - ui
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../../../deployment/site.yml
  inventory:
    host_vars:
      ui-host:
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../tests/*
scenario:
  name: ui
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
